theme: jekyll-theme-cayman
title: "Deep Spectroscopy with DESI for Photometric Redshift Training and Calibration"
description: "Documentation, codes and catalogs accompanying our paper by Biprateep Dey, Jeffrey A. Newman and the DESI Collaboration members."
